export enum SearchActionsTypes {
    ON_NEW_QUERY = "ON_NEW_QUERY",
    GET_QUERIES = "GET_QUERIES",
    TOGGLE_QUERIES_CONTAINER = "TOGGLE_QUERIES_CONTAINER",
}

export enum DataActionsTypes {
    ON_NEW_RESULTS = "ON_NEW_RESULTS",
    GET_RESULTS = "GET_RESULTS",
    ON_SEARCH_RESULTS = "ON_SEARCH_RESULTS",
    HIGHLIGHT = "HIGHLIGHT",
}